<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\mahasiswa;

class MahasiswaSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'nim'           => '2455201110002',
                'nama'          => 'Akmal Maulana Yusuf',
                'tempat_lahir'  => 'Banjarmasin',
                'tanggal_lahir' => '2006-01-01',
                'jenis_kelamin' => 'L',
                'alamat'        => '-',
                'agama'         => 'Islam',
                'no_hp'         => '-',
                'email'         => 'akmal.maulana@student.ac.id',
                'prodi'         => 'Teknik Informatika',
                'fakultas'      => 'Teknik',
                'semester'      => 2,
                'asal_sekolah'  => '-',
                'nama_ayah'     => '-',
                'nama_ibu'      => '-',
                'pekerjaan_ortu'=> '-',
            ],
            [
                'nim'           => '2455201110003',
                'nama'          => 'Halis Annisa',
                'tempat_lahir'  => 'Banjarmasin',
                'tanggal_lahir' => '2006-01-01',
                'jenis_kelamin' => 'P',
                'alamat'        => '-',
                'agama'         => 'Islam',
                'no_hp'         => '-',
                'email'         => 'halis.annisa@student.ac.id',
                'prodi'         => 'Teknik Informatika',
                'fakultas'      => 'Teknik',
                'semester'      => 2,
                'asal_sekolah'  => '-',
                'nama_ayah'     => '-',
                'nama_ibu'      => '-',
                'pekerjaan_ortu'=> '-',
            ],
            [
                'nim'           => '2455201110004',
                'nama'          => 'Hary Nur Afandi',
                'tempat_lahir'  => 'Banjarmasin',
                'tanggal_lahir' => '2006-01-01',
                'jenis_kelamin' => 'L',
                'alamat'        => '-',
                'agama'         => 'Islam',
                'no_hp'         => '-',
                'email'         => 'hary.nur@student.ac.id',
                'prodi'         => 'Teknik Informatika',
                'fakultas'      => 'Teknik',
                'semester'      => 2,
                'asal_sekolah'  => '-',
                'nama_ayah'     => '-',
                'nama_ibu'      => '-',
                'pekerjaan_ortu'=> '-',
            ],
            [
                'nim'           => '2455201110005',
                'nama'          => 'I Dewa Gede Arya Prameisa',
                'tempat_lahir'  => 'Banjarmasin',
                'tanggal_lahir' => '2006-01-01',
                'jenis_kelamin' => 'L',
                'alamat'        => '-',
                'agama'         => 'Hindu',
                'no_hp'         => '-',
                'email'         => 'idewa.arya@student.ac.id',
                'prodi'         => 'Teknik Informatika',
                'fakultas'      => 'Teknik',
                'semester'      => 2,
                'asal_sekolah'  => '-',
                'nama_ayah'     => '-',
                'nama_ibu'      => '-',
                'pekerjaan_ortu'=> '-',
            ],
            [
                'nim'           => '2455201110006',
                'nama'          => 'Luthfi Ahmad Fahrezi',
                'tempat_lahir'  => 'Banjarmasin',
                'tanggal_lahir' => '2006-01-01',
                'jenis_kelamin' => 'L',
                'alamat'        => '-',
                'agama'         => 'Islam',
                'no_hp'         => '-',
                'email'         => 'luthfi.ahmad@student.ac.id',
                'prodi'         => 'Teknik Informatika',
                'fakultas'      => 'Teknik',
                'semester'      => 2,
                'asal_sekolah'  => '-',
                'nama_ayah'     => '-',
                'nama_ibu'      => '-',
                'pekerjaan_ortu'=> '-',
            ],
            [
                'nim'           => '2455201110007',
                'nama'          => 'Luthfiana Safitri',
                'tempat_lahir'  => 'Banjarmasin',
                'tanggal_lahir' => '2006-01-01',
                'jenis_kelamin' => 'P',
                'alamat'        => '-',
                'agama'         => 'Islam',
                'no_hp'         => '-',
                'email'         => 'luthfiana.safitri@student.ac.id',
                'prodi'         => 'Teknik Informatika',
                'fakultas'      => 'Teknik',
                'semester'      => 2,
                'asal_sekolah'  => '-',
                'nama_ayah'     => '-',
                'nama_ibu'      => '-',
                'pekerjaan_ortu'=> '-',
            ],
            [
                'nim'           => '2455201110009',
                'nama'          => 'Mochammad Syahid Fariz Abqari',
                'tempat_lahir'  => 'Banjarmasin',
                'tanggal_lahir' => '2006-01-01',
                'jenis_kelamin' => 'L',
                'alamat'        => '-',
                'agama'         => 'Islam',
                'no_hp'         => '-',
                'email'         => 'mochammad.syahid@student.ac.id',
                'prodi'         => 'Teknik Informatika',
                'fakultas'      => 'Teknik',
                'semester'      => 2,
                'asal_sekolah'  => '-',
                'nama_ayah'     => '-',
                'nama_ibu'      => '-',
                'pekerjaan_ortu'=> '-',
            ],
            [
                'nim'           => '2455201110010',
                'nama'          => 'Muhammad Fajar Aulia',
                'tempat_lahir'  => 'Banjarmasin',
                'tanggal_lahir' => '2006-01-01',
                'jenis_kelamin' => 'L',
                'alamat'        => '-',
                'agama'         => 'Islam',
                'no_hp'         => '-',
                'email'         => 'muhammad.fajar@student.ac.id',
                'prodi'         => 'Teknik Informatika',
                'fakultas'      => 'Teknik',
                'semester'      => 2,
                'asal_sekolah'  => '-',
                'nama_ayah'     => '-',
                'nama_ibu'      => '-',
                'pekerjaan_ortu'=> '-',
            ],
            [
                'nim'           => '2455201110012',
                'nama'          => 'Muhammad Ryan Hidayat',
                'tempat_lahir'  => 'Banjarmasin',
                'tanggal_lahir' => '2006-01-01',
                'jenis_kelamin' => 'L',
                'alamat'        => '-',
                'agama'         => 'Islam',
                'no_hp'         => '-',
                'email'         => 'muhammad.ryan@student.ac.id',
                'prodi'         => 'Teknik Informatika',
                'fakultas'      => 'Teknik',
                'semester'      => 2,
                'asal_sekolah'  => '-',
                'nama_ayah'     => '-',
                'nama_ibu'      => '-',
                'pekerjaan_ortu'=> '-',
            ],
            [
                'nim'           => '2455201110013',
                'nama'          => 'Muhammad Syafiq Husin',
                'tempat_lahir'  => 'Banjarmasin',
                'tanggal_lahir' => '2006-01-01',
                'jenis_kelamin' => 'L',
                'alamat'        => '-',
                'agama'         => 'Islam',
                'no_hp'         => '-',
                'email'         => 'muhammad.syafiq@student.ac.id',
                'prodi'         => 'Teknik Informatika',
                'fakultas'      => 'Teknik',
                'semester'      => 2,
                'asal_sekolah'  => '-',
                'nama_ayah'     => '-',
                'nama_ibu'      => '-',
                'pekerjaan_ortu'=> '-',
            ],
            [
                'nim'           => '2455201110014',
                'nama'          => 'Muhammad Syahid Fadhilah',
                'tempat_lahir'  => 'Banjarmasin',
                'tanggal_lahir' => '2006-01-01',
                'jenis_kelamin' => 'L',
                'alamat'        => '-',
                'agama'         => 'Islam',
                'no_hp'         => '-',
                'email'         => 'muhammad.syahid.f@student.ac.id',
                'prodi'         => 'Teknik Informatika',
                'fakultas'      => 'Teknik',
                'semester'      => 2,
                'asal_sekolah'  => '-',
                'nama_ayah'     => '-',
                'nama_ibu'      => '-',
                'pekerjaan_ortu'=> '-',
            ],
            [
                'nim'           => '2455201110015',
                'nama'          => 'Muhammad Syarif',
                'tempat_lahir'  => 'Banjarmasin',
                'tanggal_lahir' => '2006-01-01',
                'jenis_kelamin' => 'L',
                'alamat'        => '-',
                'agama'         => 'Islam',
                'no_hp'         => '-',
                'email'         => 'muhammad.syarif@student.ac.id',
                'prodi'         => 'Teknik Informatika',
                'fakultas'      => 'Teknik',
                'semester'      => 2,
                'asal_sekolah'  => '-',
                'nama_ayah'     => '-',
                'nama_ibu'      => '-',
                'pekerjaan_ortu'=> '-',
            ],
            [
                'nim'           => '2455201110016',
                'nama'          => 'Nanda Syalwa Nazella',
                'tempat_lahir'  => 'Banjarmasin',
                'tanggal_lahir' => '2006-01-01',
                'jenis_kelamin' => 'P',
                'alamat'        => '-',
                'agama'         => 'Islam',
                'no_hp'         => '-',
                'email'         => 'nanda.syalwa@student.ac.id',
                'prodi'         => 'Teknik Informatika',
                'fakultas'      => 'Teknik',
                'semester'      => 2,
                'asal_sekolah'  => '-',
                'nama_ayah'     => '-',
                'nama_ibu'      => '-',
                'pekerjaan_ortu'=> '-',
            ],
            [
                'nim'           => '2455201110017',
                'nama'          => 'Nazwa Aulia Putri',
                'tempat_lahir'  => 'Banjarmasin',
                'tanggal_lahir' => '2006-01-01',
                'jenis_kelamin' => 'P',
                'alamat'        => '-',
                'agama'         => 'Islam',
                'no_hp'         => '-',
                'email'         => 'nazwa.aulia@student.ac.id',
                'prodi'         => 'Teknik Informatika',
                'fakultas'      => 'Teknik',
                'semester'      => 2,
                'asal_sekolah'  => '-',
                'nama_ayah'     => '-',
                'nama_ibu'      => '-',
                'pekerjaan_ortu'=> '-',
            ],
            [
                'nim'           => '2455201110018',
                'nama'          => 'Nor Mayanti',
                'tempat_lahir'  => 'Banjarmasin',
                'tanggal_lahir' => '2006-01-01',
                'jenis_kelamin' => 'P',
                'alamat'        => '-',
                'agama'         => 'Islam',
                'no_hp'         => '-',
                'email'         => 'nor.mayanti@student.ac.id',
                'prodi'         => 'Teknik Informatika',
                'fakultas'      => 'Teknik',
                'semester'      => 2,
                'asal_sekolah'  => '-',
                'nama_ayah'     => '-',
                'nama_ibu'      => '-',
                'pekerjaan_ortu'=> '-',
            ],
            [
                'nim'           => '2455201110019',
                'nama'          => 'Nur Aisyah',
                'tempat_lahir'  => 'Banjarmasin',
                'tanggal_lahir' => '2006-01-01',
                'jenis_kelamin' => 'P',
                'alamat'        => '-',
                'agama'         => 'Islam',
                'no_hp'         => '-',
                'email'         => 'nur.aisyah@student.ac.id',
                'prodi'         => 'Teknik Informatika',
                'fakultas'      => 'Teknik',
                'semester'      => 2,
                'asal_sekolah'  => '-',
                'nama_ayah'     => '-',
                'nama_ibu'      => '-',
                'pekerjaan_ortu'=> '-',
            ],
            [
                'nim'           => '2455201110020',
                'nama'          => 'Pendri Mikola',
                'tempat_lahir'  => 'Banjarmasin',
                'tanggal_lahir' => '2006-01-01',
                'jenis_kelamin' => 'L',
                'alamat'        => '-',
                'agama'         => 'Islam',
                'no_hp'         => '-',
                'email'         => 'pendri.mikola@student.ac.id',
                'prodi'         => 'Teknik Informatika',
                'fakultas'      => 'Teknik',
                'semester'      => 2,
                'asal_sekolah'  => '-',
                'nama_ayah'     => '-',
                'nama_ibu'      => '-',
                'pekerjaan_ortu'=> '-',
            ],
            [
                'nim'           => '2455201110021',
                'nama'          => 'Raihan',
                'tempat_lahir'  => 'Banjarmasin',
                'tanggal_lahir' => '2006-01-01',
                'jenis_kelamin' => 'L',
                'alamat'        => '-',
                'agama'         => 'Islam',
                'no_hp'         => '-',
                'email'         => 'raihan@student.ac.id',
                'prodi'         => 'Teknik Informatika',
                'fakultas'      => 'Teknik',
                'semester'      => 2,
                'asal_sekolah'  => '-',
                'nama_ayah'     => '-',
                'nama_ibu'      => '-',
                'pekerjaan_ortu'=> '-',
            ],
            [
                'nim'           => '2455201110022',
                'nama'          => 'Rianti',
                'tempat_lahir'  => 'Banjarmasin',
                'tanggal_lahir' => '2006-01-01',
                'jenis_kelamin' => 'P',
                'alamat'        => '-',
                'agama'         => 'Islam',
                'no_hp'         => '-',
                'email'         => 'rianti@student.ac.id',
                'prodi'         => 'Teknik Informatika',
                'fakultas'      => 'Teknik',
                'semester'      => 2,
                'asal_sekolah'  => '-',
                'nama_ayah'     => '-',
                'nama_ibu'      => '-',
                'pekerjaan_ortu'=> '-',
            ],
            [
                'nim'           => '2455201110023',
                'nama'          => 'Rudi Gunawan',
                'tempat_lahir'  => 'Banjarmasin',
                'tanggal_lahir' => '2006-01-01',
                'jenis_kelamin' => 'L',
                'alamat'        => '-',
                'agama'         => 'Islam',
                'no_hp'         => '-',
                'email'         => 'rudi.gunawan@student.ac.id',
                'prodi'         => 'Teknik Informatika',
                'fakultas'      => 'Teknik',
                'semester'      => 2,
                'asal_sekolah'  => '-',
                'nama_ayah'     => '-',
                'nama_ibu'      => '-',
                'pekerjaan_ortu'=> '-',
            ],
            [
                'nim'           => '2455201110024',
                'nama'          => 'Siti Hidayatuz Zuhro',
                'tempat_lahir'  => 'Banjarmasin',
                'tanggal_lahir' => '2006-01-01',
                'jenis_kelamin' => 'P',
                'alamat'        => '-',
                'agama'         => 'Islam',
                'no_hp'         => '-',
                'email'         => 'siti.hidayatuz@student.ac.id',
                'prodi'         => 'Teknik Informatika',
                'fakultas'      => 'Teknik',
                'semester'      => 2,
                'asal_sekolah'  => '-',
                'nama_ayah'     => '-',
                'nama_ibu'      => '-',
                'pekerjaan_ortu'=> '-',
            ],
            [
                'nim'           => '2455201110025',
                'nama'          => 'Viona Winola Suprapto',
                'tempat_lahir'  => 'Banjarmasin',
                'tanggal_lahir' => '2006-01-01',
                'jenis_kelamin' => 'P',
                'alamat'        => '-',
                'agama'         => 'Islam',
                'no_hp'         => '-',
                'email'         => 'viona.winola@student.ac.id',
                'prodi'         => 'Teknik Informatika',
                'fakultas'      => 'Teknik',
                'semester'      => 2,
                'asal_sekolah'  => '-',
                'nama_ayah'     => '-',
                'nama_ibu'      => '-',
                'pekerjaan_ortu'=> '-',
            ],
            [
                'nim'           => '2455201110026',
                'nama'          => 'Yudha Maulana Darham',
                'tempat_lahir'  => 'Banjarmasin',
                'tanggal_lahir' => '2006-01-01',
                'jenis_kelamin' => 'L',
                'alamat'        => '-',
                'agama'         => 'Islam',
                'no_hp'         => '-',
                'email'         => 'yudha.maulana@student.ac.id',
                'prodi'         => 'Teknik Informatika',
                'fakultas'      => 'Teknik',
                'semester'      => 2,
                'asal_sekolah'  => '-',
                'nama_ayah'     => '-',
                'nama_ibu'      => '-',
                'pekerjaan_ortu'=> '-',
            ],
            [
                'nim'           => '2455201110027',
                'nama'          => 'Zainabul Askyah',
                'tempat_lahir'  => 'Banjarmasin',
                'tanggal_lahir' => '2006-01-01',
                'jenis_kelamin' => 'P',
                'alamat'        => '-',
                'agama'         => 'Islam',
                'no_hp'         => '-',
                'email'         => 'zainabul.askyah@student.ac.id',
                'prodi'         => 'Teknik Informatika',
                'fakultas'      => 'Teknik',
                'semester'      => 2,
                'asal_sekolah'  => '-',
                'nama_ayah'     => '-',
                'nama_ibu'      => '-',
                'pekerjaan_ortu'=> '-',
            ],
            [
                'nim'           => '2455201110028',
                'nama'          => 'Muhammad Agus Yuliansyah',
                'tempat_lahir'  => 'Banjarmasin',
                'tanggal_lahir' => '2006-01-01',
                'jenis_kelamin' => 'L',
                'alamat'        => '-',
                'agama'         => 'Islam',
                'no_hp'         => '-',
                'email'         => 'muhammad.agus@student.ac.id',
                'prodi'         => 'Teknik Informatika',
                'fakultas'      => 'Teknik',
                'semester'      => 2,
                'asal_sekolah'  => '-',
                'nama_ayah'     => '-',
                'nama_ibu'      => '-',
                'pekerjaan_ortu'=> '-',
            ],
            [
                'nim'           => '2455201110030',
                'nama'          => 'Gilang Hernawan Salem',
                'tempat_lahir'  => 'Banjarmasin',
                'tanggal_lahir' => '2006-01-01',
                'jenis_kelamin' => 'L',
                'alamat'        => '-',
                'agama'         => 'Islam',
                'no_hp'         => '-',
                'email'         => 'gilang.hernawan@student.ac.id',
                'prodi'         => 'Teknik Informatika',
                'fakultas'      => 'Teknik',
                'semester'      => 2,
                'asal_sekolah'  => '-',
                'nama_ayah'     => '-',
                'nama_ibu'      => '-',
                'pekerjaan_ortu'=> '-',
            ],
            [
                'nim'           => '2455201110031',
                'nama'          => 'Sahidatul Asiah',
                'tempat_lahir'  => 'Banjarmasin',
                'tanggal_lahir' => '2006-01-01',
                'jenis_kelamin' => 'P',
                'alamat'        => '-',
                'agama'         => 'Islam',
                'no_hp'         => '-',
                'email'         => 'sahidatul.asiah@student.ac.id',
                'prodi'         => 'Teknik Informatika',
                'fakultas'      => 'Teknik',
                'semester'      => 2,
                'asal_sekolah'  => '-',
                'nama_ayah'     => '-',
                'nama_ibu'      => '-',
                'pekerjaan_ortu'=> '-',
            ],
        ];

        foreach ($data as $row) {
            mahasiswa::firstOrCreate(
                ['nim' => $row['nim']],
                $row
            );
        }
    }
}
